[package]
name = "r2l-macros"
version = "0.0.1"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
itertools = "0.14.0"
proc-macro2 = { version = "1.0.95" }
quote = { version = "1.0.40" }
syn = { version = "2.0.101", features = ["full", "extra-traits"] }
