[package]
name = "r2l-benchmark-worker"
version.workspace = true
edition.workspace = true
description = "Worker for executing r2l benchmark tasks"
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
r2l = { workspace = true, features = ["gym"] }
r2l-benchmark-task = { workspace = true }
serde_json = "1.0.151"
anyhow = { workspace = true }

[lints]
workspace = true
